services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports: ["8080:80"]
    container_name: frontend
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports: 
      - "5556:5556"
    env_file:
      - backend/.env
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:17-alpine
    container_name: postgres
    env_file:
      - postgres/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
